includes:
- ./text.yaml
- configs/datasets/memes_binary/bert.yaml
- configs/models/unimodal/bert.yaml

model_config:
  unimodal_text:
    num_labels: 2
    classifier:
      type: mlp
      params:
        in_dim: 768
        num_layers: 2
        out_dim: 2

training:
  batch_size: 32
