model_config:
  unimodal_text:
    num_labels: 4
    classifier:
      type: mlp
      params:
        num_layers: 2
    losses:
    - type: cross_entropy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

evaluation:
  metrics:
    - accuracy
    - macro_f1
    - recall_macro
    - precision_macro
    - mae
    - mmae_tgt

training:
  batch_size: 16
  lr_scheduler: true
  max_updates: 3000
  early_stop:
    criteria: memes_tgt/macro_f1
    minimize: false

checkpoint:
  pretrained_state_mapping:
    base: base
