includes:
- ./classification.yaml
- configs/datasets/memes/bert.yaml

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
    metrics:
    - accuracy
    - macro_f1
    - recall_macro
    - precision_macro
    - mae
    - mmae
training:
  batch_size: 16
  lr_scheduler: true
  max_updates: 3200
  early_stop:
    criteria: memes/macro_f1
    minimize: false

checkpoint:
  pretrained_state_mapping:
    bert: bert
